export type VendorCategory = "musica" | "catering" | "fotografia" | "venues" | "decoracion";

export interface Vendor {
  id: string;
  name: string;
  category: VendorCategory;
  categoryLabel: string;
  location: string;
  basePrice: number;
  priceUnit: string;
  rating: number;
  reviews: number;
  verified: boolean;
  fechas2026: boolean;
  tagline: string;
  includes: string[];
  images: string[];
  bookedDates: string[]; // ISO dates not available
  popularity: number;
}

export const CATEGORIES: { slug: VendorCategory; label: string }[] = [
  { slug: "musica", label: "Música" },
  { slug: "catering", label: "Catering" },
  { slug: "fotografia", label: "Fotografía" },
  { slug: "venues", label: "Venues" },
  { slug: "decoracion", label: "Decoración" },
];

const px = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2`;

export const VENDORS: Vendor[] = [
  {
    id: "dj-set-audio",
    name: "DJ Set + Audio Profesional",
    category: "musica",
    categoryLabel: "Música",
    location: "CDMX",
    basePrice: 18500,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 132,
    verified: true,
    fechas2026: true,
    tagline: "DJ, iluminación y sonido para una noche memorable.",
    includes: ["DJ 6 horas en vivo", "Sistema de audio line array", "Iluminación robótica", "Coordinación de playlist previa"],
    images: [px(1763075), px(1486974), px(1190297)],
    bookedDates: ["2026-09-12", "2026-09-19", "2026-10-03", "2026-11-21"],
    popularity: 98,
  },
  {
    id: "mariachi-herencia",
    name: "Mariachi Herencia",
    category: "musica",
    categoryLabel: "Música",
    location: "Guadalajara",
    basePrice: 12000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 89,
    verified: true,
    fechas2026: true,
    tagline: "Mariachi tradicional de 8 elementos para ceremonia y recepción.",
    includes: ["8 músicos en vivo", "2 sets de 45 minutos", "Repertorio a petición", "Vestimenta gala"],
    images: [px(1763067), px(167491), px(2100774)],
    bookedDates: ["2026-09-05", "2026-10-10"],
    popularity: 74,
  },
  {
    id: "banquete-signature",
    name: "Banquete Signature",
    category: "catering",
    categoryLabel: "Catering",
    location: "CDMX",
    basePrice: 950,
    priceUnit: "por persona",
    rating: 4.9,
    reviews: 214,
    verified: true,
    fechas2026: true,
    tagline: "Menú de tres tiempos, montaje y servicio incluido.",
    includes: ["Menú de 3 tiempos", "Meseros y capitán", "Cristalería y loza", "Degustación previa para 2"],
    images: [px(958545), px(262978), px(1640777)],
    bookedDates: ["2026-09-26", "2026-10-17", "2026-12-05"],
    popularity: 96,
  },
  {
    id: "barra-mixologia",
    name: "Barra de Mixología Artesanal",
    category: "catering",
    categoryLabel: "Catering",
    location: "Monterrey",
    basePrice: 14500,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 61,
    verified: false,
    fechas2026: true,
    tagline: "Cócteles de autor y barra iluminada para tu recepción.",
    includes: ["2 mixólogos 5 horas", "Menú de 6 cócteles", "Barra iluminada LED", "Insumos premium incluidos"],
    images: [px(1283219), px(613037), px(27929030)],
    bookedDates: ["2026-09-12"],
    popularity: 68,
  },
  {
    id: "foto-video-cinematico",
    name: "Foto y Video Cinemático",
    category: "fotografia",
    categoryLabel: "Fotografía",
    location: "CDMX",
    basePrice: 24000,
    priceUnit: "por evento",
    rating: 5.0,
    reviews: 178,
    verified: true,
    fechas2026: true,
    tagline: "Cobertura 4K, drone y entrega de highlights.",
    includes: ["2 fotógrafos + filmmaker", "Video highlight 5 min", "Drone y cobertura aérea", "Galería en línea 12 meses"],
    images: [px(1264210), px(169198), px(169190)],
    bookedDates: ["2026-09-19", "2026-09-26", "2026-10-24", "2026-11-14"],
    popularity: 99,
  },
  {
    id: "cabina-fotos-360",
    name: "Cabina de Fotos 360°",
    category: "fotografia",
    categoryLabel: "Fotografía",
    location: "Puebla",
    basePrice: 7800,
    priceUnit: "por evento",
    rating: 4.6,
    reviews: 47,
    verified: false,
    fechas2026: false,
    tagline: "Videos 360° con overlays personalizados para tus invitados.",
    includes: ["Plataforma 360° 4 horas", "Overlays con tu branding", "Entrega instantánea por QR", "Props y animador"],
    images: [px(3171770), px(2253879), px(2747449)],
    bookedDates: [],
    popularity: 55,
  },
  {
    id: "jardin-los-olivos",
    name: "Jardín Los Olivos",
    category: "venues",
    categoryLabel: "Venues",
    location: "CDMX",
    basePrice: 42000,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 156,
    verified: true,
    fechas2026: true,
    tagline: "Venue para hasta 180 invitados en la ciudad.",
    includes: ["Jardín + terraza techada", "Capacidad 180 invitados", "Mobiliario lounge incluido", "Estacionamiento y valet"],
    images: [px(169198), px(265947), px(1729797)],
    bookedDates: ["2026-09-05", "2026-09-12", "2026-09-19", "2026-10-03", "2026-10-10", "2026-10-17"],
    popularity: 93,
  },
  {
    id: "hacienda-santa-rosa",
    name: "Hacienda Santa Rosa",
    category: "venues",
    categoryLabel: "Venues",
    location: "Querétaro",
    basePrice: 68000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 98,
    verified: true,
    fechas2026: true,
    tagline: "Hacienda del siglo XVIII con capilla y jardines.",
    includes: ["Uso exclusivo 12 horas", "Capilla consagrada", "Jardines y andadores", "Suite nupcial incluida"],
    images: [px(1523438885), px(1511285560929), px(587741)],
    bookedDates: ["2026-09-26", "2026-11-07"],
    popularity: 88,
  },
  {
    id: "diseno-floral-editorial",
    name: "Diseño Floral Editorial",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "CDMX",
    basePrice: 16800,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 121,
    verified: true,
    fechas2026: true,
    tagline: "Flores de temporada, mesas y ceremonia.",
    includes: ["Propuesta de diseño 3D", "Centros de mesa", "Arco de ceremonia", "Ramo y boutonnieres"],
    images: [px(931179), px(1729797), px(1507504031)],
    bookedDates: ["2026-10-03", "2026-10-24"],
    popularity: 91,
  },
  {
    id: "iluminacion-arquitectonica",
    name: "Iluminación Arquitectónica",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "Monterrey",
    basePrice: 11500,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 54,
    verified: false,
    fechas2026: true,
    tagline: "Uplighting, guirnaldas cálidas y proyección de monograma.",
    includes: ["40 luminarias LED", "Guirnaldas cálidas", "Monograma proyectado", "Técnico durante el evento"],
    images: [px(1585325), px(260239), px(169190)],
    bookedDates: ["2026-09-19"],
    popularity: 62,
  },
  {
    id: "coordinacion-del-dia",
    name: "Coordinación del Día",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "CDMX",
    basePrice: 12500,
    priceUnit: "por evento",
    rating: 5.0,
    reviews: 143,
    verified: true,
    fechas2026: true,
    tagline: "Un equipo experto para que tú disfrutes.",
    includes: ["Coordinadora + 2 asistentes", "Timeline del evento", "Ensayo de ceremonia", "Kit de emergencia"],
    images: [px(1190297), px(265947), px(931179)],
    bookedDates: ["2026-09-12", "2026-10-10", "2026-12-05"],
    popularity: 85,
  },
  {
    id: "grupo-norteño-live",
    name: "Grupo Norteño Live",
    category: "musica",
    categoryLabel: "Música",
    location: "Monterrey",
    basePrice: 22000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 76,
    verified: true,
    fechas2026: false,
    tagline: "Norteño con sax para prender la pista toda la noche.",
    includes: ["6 músicos en vivo", "3 sets de 50 minutos", "Audio e iluminación básica", "Canción especial aprendida"],
    images: [px(1190298), px(1105666), px(1763075)],
    bookedDates: ["2026-09-26", "2026-10-17"],
    popularity: 71,
  },
];

export const PRICE_RANGES = [
  { id: "0-10000", label: "Hasta $10,000", min: 0, max: 10000 },
  { id: "10000-20000", label: "$10,000 – $20,000", min: 10000, max: 20000 },
  { id: "20000-45000", label: "$20,000 – $45,000", min: 20000, max: 45000 },
  { id: "45000-plus", label: "Más de $45,000", min: 45000, max: Infinity },
] as const;

export function formatMXN(value: number) {
  return `$${value.toLocaleString("es-MX")} MXN`;
}
