export type VendorCategory =
  | "musica"
  | "catering"
  | "fotografia"
  | "venues"
  | "decoracion"
  | "mesa-de-dulces"
  | "pasteleria"
  | "vestidos-novia"
  | "trajes-tuxedos"
  | "autos-limosinas";

export interface Vendor {
  id: string;
  name: string;
  category: VendorCategory;
  categoryLabel: string;
  location: string;
  basePrice: number;
  priceUnit: string;
  rating: number;
  reviews: number;
  verified: boolean;
  fechas2026: boolean;
  tagline: string;
  includes: string[];
  images: string[];
  bookedDates: string[]; // ISO dates not available
  popularity: number;
}

export const CATEGORIES: { slug: VendorCategory; label: string }[] = [
  { slug: "musica", label: "Música" },
  { slug: "catering", label: "Catering" },
  { slug: "fotografia", label: "Fotografía" },
  { slug: "venues", label: "Venues" },
  { slug: "decoracion", label: "Decoración" },
  { slug: "mesa-de-dulces", label: "Mesa de Dulces" },
  { slug: "pasteleria", label: "Pastelería y Repostería" },
  { slug: "vestidos-novia", label: "Vestidos de Novia" },
  { slug: "trajes-tuxedos", label: "Trajes y Tuxedos" },
  { slug: "autos-limosinas", label: "Renta de Autos y Limosinas" },
];

const px = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&fm=webp`;

export const VENDORS: Vendor[] = [
  {
    id: "dj-set-audio",
    name: "DJ Set + Audio Profesional",
    category: "musica",
    categoryLabel: "Música",
    location: "CDMX",
    basePrice: 18500,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 132,
    verified: true,
    fechas2026: true,
    tagline: "DJ, iluminación y sonido para una noche memorable.",
    includes: ["DJ 6 horas en vivo", "Sistema de audio line array", "Iluminación robótica", "Coordinación de playlist previa"],
    images: [px(9271241), px(9376869), px(1105666)],
    bookedDates: ["2026-09-12", "2026-09-19", "2026-10-03", "2026-11-21"],
    popularity: 98,
  },
  {
    id: "mariachi-herencia",
    name: "Mariachi Herencia",
    category: "musica",
    categoryLabel: "Música",
    location: "Guadalajara",
    basePrice: 12000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 89,
    verified: true,
    fechas2026: true,
    tagline: "Mariachi tradicional de 8 elementos para ceremonia y recepción.",
    includes: ["8 músicos en vivo", "2 sets de 45 minutos", "Repertorio a petición", "Vestimenta gala"],
    images: [px(7772389), px(8638205), px(1763067)],
    bookedDates: ["2026-09-05", "2026-10-10"],
    popularity: 74,
  },
  {
    id: "banquete-signature",
    name: "Banquete Signature",
    category: "catering",
    categoryLabel: "Catering",
    location: "CDMX",
    basePrice: 950,
    priceUnit: "por persona",
    rating: 4.9,
    reviews: 214,
    verified: true,
    fechas2026: true,
    tagline: "Menú de tres tiempos, montaje y servicio incluido.",
    includes: ["Menú de 3 tiempos", "Meseros y capitán", "Cristalería y loza", "Degustación previa para 2"],
    images: [px(262978), px(1729797), px(1640777)],
    bookedDates: ["2026-09-26", "2026-10-17", "2026-12-05"],
    popularity: 96,
  },
  {
    id: "barra-mixologia",
    name: "Barra de Mixología Artesanal",
    category: "catering",
    categoryLabel: "Catering",
    location: "Monterrey",
    basePrice: 14500,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 61,
    verified: false,
    fechas2026: true,
    tagline: "Cócteles de autor y barra iluminada para tu recepción.",
    includes: ["2 mixólogos 5 horas", "Menú de 6 cócteles", "Barra iluminada LED", "Insumos premium incluidos"],
    images: [px(3171770), px(613037), px(1283219)],
    bookedDates: ["2026-09-12"],
    popularity: 68,
  },
  {
    id: "foto-video-cinematico",
    name: "Foto y Video Cinemático",
    category: "fotografia",
    categoryLabel: "Fotografía",
    location: "CDMX",
    basePrice: 24000,
    priceUnit: "por evento",
    rating: 5.0,
    reviews: 178,
    verified: true,
    fechas2026: true,
    tagline: "Cobertura 4K, drone y entrega de highlights.",
    includes: ["2 fotógrafos + filmmaker", "Video highlight 5 min", "Drone y cobertura aérea", "Galería en línea 12 meses"],
    images: [px(33072063), px(35325793), px(1264210)],
    bookedDates: ["2026-09-19", "2026-09-26", "2026-10-24", "2026-11-14"],
    popularity: 99,
  },
  {
    id: "cabina-fotos-360",
    name: "Cabina de Fotos 360°",
    category: "fotografia",
    categoryLabel: "Fotografía",
    location: "Puebla",
    basePrice: 7800,
    priceUnit: "por evento",
    rating: 4.6,
    reviews: 47,
    verified: false,
    fechas2026: false,
    tagline: "Videos 360° con overlays personalizados para tus invitados.",
    includes: ["Plataforma 360° 4 horas", "Overlays con tu branding", "Entrega instantánea por QR", "Props y animador"],
    images: [px(2606402), px(6312032), px(13788485)],
    bookedDates: [],
    popularity: 55,
  },
  {
    id: "jardin-los-olivos",
    name: "Jardín Los Olivos",
    category: "venues",
    categoryLabel: "Venues",
    location: "CDMX",
    basePrice: 42000,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 156,
    verified: true,
    fechas2026: true,
    tagline: "Venue para hasta 180 invitados en la ciudad.",
    includes: ["Jardín + terraza techada", "Capacidad 180 invitados", "Mobiliario lounge incluido", "Estacionamiento y valet"],
    images: [px(169198), px(9375427), px(265947)],
    bookedDates: ["2026-09-05", "2026-09-12", "2026-09-19", "2026-10-03", "2026-10-10", "2026-10-17"],
    popularity: 93,
  },
  {
    id: "hacienda-santa-rosa",
    name: "Hacienda Santa Rosa",
    category: "venues",
    categoryLabel: "Venues",
    location: "Querétaro",
    basePrice: 68000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 98,
    verified: true,
    fechas2026: true,
    tagline: "Hacienda del siglo XVIII con capilla y jardines.",
    includes: ["Uso exclusivo 12 horas", "Capilla consagrada", "Jardines y andadores", "Suite nupcial incluida"],
    images: [px(20773426), px(14399423), px(19676073)],
    bookedDates: ["2026-09-26", "2026-11-07"],
    popularity: 88,
  },
  {
    id: "diseno-floral-editorial",
    name: "Diseño Floral Editorial",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "CDMX",
    basePrice: 16800,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 121,
    verified: true,
    fechas2026: true,
    tagline: "Flores de temporada, mesas y ceremonia.",
    includes: ["Propuesta de diseño 3D", "Centros de mesa", "Arco de ceremonia", "Ramo y boutonnieres"],
    images: [px(931179), px(1702370), px(169190)],
    bookedDates: ["2026-10-03", "2026-10-24"],
    popularity: 91,
  },
  {
    id: "iluminacion-arquitectonica",
    name: "Iluminación Arquitectónica",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "Monterrey",
    basePrice: 11500,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 54,
    verified: false,
    fechas2026: true,
    tagline: "Uplighting, guirnaldas cálidas y proyección de monograma.",
    includes: ["40 luminarias LED", "Guirnaldas cálidas", "Monograma proyectado", "Técnico durante el evento"],
    images: [px(9703891), px(15964954), px(37975404)],
    bookedDates: ["2026-09-19"],
    popularity: 62,
  },
  {
    id: "coordinacion-del-dia",
    name: "Coordinación del Día",
    category: "decoracion",
    categoryLabel: "Decoración",
    location: "CDMX",
    basePrice: 12500,
    priceUnit: "por evento",
    rating: 5.0,
    reviews: 143,
    verified: true,
    fechas2026: true,
    tagline: "Un equipo experto para que tú disfrutes.",
    includes: ["Coordinadora + 2 asistentes", "Timeline del evento", "Ensayo de ceremonia", "Kit de emergencia"],
    images: [px(15964967), px(15964962), px(9375427)],
    bookedDates: ["2026-09-12", "2026-10-10", "2026-12-05"],
    popularity: 85,
  },
  {
    id: "grupo-norteño-live",
    name: "Grupo Norteño Live",
    category: "musica",
    categoryLabel: "Música",
    location: "Monterrey",
    basePrice: 22000,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 76,
    verified: true,
    fechas2026: false,
    tagline: "Norteño con sax para prender la pista toda la noche.",
    includes: ["6 músicos en vivo", "3 sets de 50 minutos", "Audio e iluminación básica", "Canción especial aprendida"],
    images: [px(12179197), px(1190297), px(2747449)],
    bookedDates: ["2026-09-26", "2026-10-17"],
    popularity: 71,
  },
  {
    id: "dulce-mesa-studio",
    name: "Dulce Mesa Studio",
    category: "mesa-de-dulces",
    categoryLabel: "Mesa de Dulces",
    location: "CDMX",
    basePrice: 8900,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 112,
    verified: true,
    fechas2026: true,
    tagline: "Mesa de dulces temática con diseño a la medida de tu evento.",
    includes: ["Diseño personalizado", "40+ piezas por invitado", "Backdrop y letrero", "Montaje y desmontaje"],
    images: [px(587741), px(10364951), px(5682489)],
    bookedDates: ["2026-09-12", "2026-10-03"],
    popularity: 82,
  },
  {
    id: "candy-bar-luxury",
    name: "Candy Bar Luxury",
    category: "mesa-de-dulces",
    categoryLabel: "Mesa de Dulces",
    location: "Guadalajara",
    basePrice: 6500,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 64,
    verified: true,
    fechas2026: true,
    tagline: "Candy bar premium con dulces importados y cristalería.",
    includes: ["Dulces importados", "Cristalería vintage", "Bolsitas para invitados", "Atención 4 horas"],
    images: [px(10364951), px(14017645), px(12068771)],
    bookedDates: ["2026-09-19"],
    popularity: 63,
  },
  {
    id: "sugar-and-bloom",
    name: "Sugar & Bloom",
    category: "mesa-de-dulces",
    categoryLabel: "Mesa de Dulces",
    location: "Monterrey",
    basePrice: 11200,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 91,
    verified: false,
    fechas2026: false,
    tagline: "Mesa de dulces con flores naturales y estación de postres vivos.",
    includes: ["Estación de postres en vivo", "Flores naturales", "Carrito de algodón", "Personal uniformado"],
    images: [px(5682489), px(2072173), px(239325)],
    bookedDates: ["2026-10-10", "2026-11-14"],
    popularity: 70,
  },
  {
    id: "pasteleria-maison",
    name: "Pastelería Maison",
    category: "pasteleria",
    categoryLabel: "Pastelería y Repostería",
    location: "CDMX",
    basePrice: 5400,
    priceUnit: "por pastel",
    rating: 5.0,
    reviews: 187,
    verified: true,
    fechas2026: true,
    tagline: "Pasteles de boda de autor, hasta 5 pisos, con degustación incluida.",
    includes: ["Degustación para 4 personas", "Diseño 3D del pastel", "Hasta 5 pisos", "Entrega y montaje"],
    images: [px(10751391), px(291528), px(12068771)],
    bookedDates: ["2026-09-05", "2026-09-26", "2026-10-17"],
    popularity: 94,
  },
  {
    id: "reposteria-anto",
    name: "Repostería Anto",
    category: "pasteleria",
    categoryLabel: "Pastelería y Repostería",
    location: "Puebla",
    basePrice: 3800,
    priceUnit: "por pastel",
    rating: 4.8,
    reviews: 76,
    verified: true,
    fechas2026: true,
    tagline: "Pasteles artesanales, mesa de postres minis y macarons.",
    includes: ["Pastel de 3 pisos", "50 mini postres", "Torre de macarons", "Cake topper personalizado"],
    images: [px(1055272), px(1120970), px(5682489)],
    bookedDates: ["2026-10-24"],
    popularity: 66,
  },
  {
    id: "atelier-delice",
    name: "Atelier Délice",
    category: "pasteleria",
    categoryLabel: "Pastelería y Repostería",
    location: "Querétaro",
    basePrice: 7200,
    priceUnit: "por pastel",
    rating: 4.9,
    reviews: 58,
    verified: false,
    fechas2026: false,
    tagline: "Alta repostería francesa: croquembouche, entremets y más.",
    includes: ["Croquembouche o pastel francés", "Estación de café pairing", "Opciones sin gluten/veganas", "Servicio de corte"],
    images: [px(17315403), px(14017645), px(239325)],
    bookedDates: [],
    popularity: 58,
  },
  {
    id: "novia-eterea",
    name: "Novia Etérea Atelier",
    category: "vestidos-novia",
    categoryLabel: "Vestidos de Novia",
    location: "CDMX",
    basePrice: 35000,
    priceUnit: "por vestido",
    rating: 4.9,
    reviews: 143,
    verified: true,
    fechas2026: true,
    tagline: "Vestidos de diseñador a la medida con 3 pruebas incluidas.",
    includes: ["Diseño a la medida", "3 citas de prueba", "Velo y tocado", "Ajustes finales ilimitados"],
    images: [px(8459382), px(20352726), px(20352729)],
    bookedDates: ["2026-09-12", "2026-10-03", "2026-10-24"],
    popularity: 90,
  },
  {
    id: "casa-maria-novias",
    name: "Casa María Novias",
    category: "vestidos-novia",
    categoryLabel: "Vestidos de Novia",
    location: "Guadalajara",
    basePrice: 18900,
    priceUnit: "por vestido",
    rating: 4.7,
    reviews: 98,
    verified: true,
    fechas2026: true,
    tagline: "Colección prêt-à-porter y renta de vestidos de gala.",
    includes: ["Renta o compra", "2 citas de ajuste", "Accesorios incluidos", "Planchado y entrega"],
    images: [px(15868533), px(8459398), px(7140404)],
    bookedDates: ["2026-09-19"],
    popularity: 77,
  },
  {
    id: "boutique-verona",
    name: "Boutique Verona",
    category: "vestidos-novia",
    categoryLabel: "Vestidos de Novia",
    location: "Monterrey",
    basePrice: 26000,
    priceUnit: "por vestido",
    rating: 4.8,
    reviews: 67,
    verified: false,
    fechas2026: false,
    tagline: "Vestidos importados de casas europeas y cita con champaña.",
    includes: ["Marcas europeas exclusivas", "Cita privada con champaña", "Modista en boutique", "Segunda prueba virtual"],
    images: [px(20352727), px(8459382), px(15868533)],
    bookedDates: ["2026-11-07"],
    popularity: 60,
  },
  {
    id: "sastreria-napoli",
    name: "Sastrería Napoli",
    category: "trajes-tuxedos",
    categoryLabel: "Trajes y Tuxedos",
    location: "CDMX",
    basePrice: 9800,
    priceUnit: "por traje",
    rating: 4.9,
    reviews: 121,
    verified: true,
    fechas2026: true,
    tagline: "Tuxedos a la medida con telas italianas y 2 pruebas.",
    includes: ["Tela italiana Super 120s", "2 citas de prueba", "Camisa y corbata", "Entrega express 3 semanas"],
    images: [px(325876), px(35505716), px(1043474)],
    bookedDates: ["2026-09-26", "2026-10-10"],
    popularity: 86,
  },
  {
    id: "tux-rental-gala",
    name: "Gala Tux Rental",
    category: "trajes-tuxedos",
    categoryLabel: "Trajes y Tuxedos",
    location: "Monterrey",
    basePrice: 3200,
    priceUnit: "por renta",
    rating: 4.6,
    reviews: 84,
    verified: true,
    fechas2026: true,
    tagline: "Renta de tuxedos y smokings para novio y padrinos.",
    includes: ["Renta 72 horas", "Paquete novio + 5 padrinos", "Ajustes incluidos", "Tintorería posterior"],
    images: [px(26664575), px(29080966), px(9334752)],
    bookedDates: ["2026-09-05", "2026-12-05"],
    popularity: 72,
  },
  {
    id: "sartoria-milano",
    name: "Sartoria Milano",
    category: "trajes-tuxedos",
    categoryLabel: "Trajes y Tuxedos",
    location: "Guadalajara",
    basePrice: 14500,
    priceUnit: "por traje",
    rating: 4.8,
    reviews: 52,
    verified: false,
    fechas2026: false,
    tagline: "Traje sastre bespoke completo: chaqué, frac o tuxedo.",
    includes: ["Bespoke 100% a la medida", "3 pruebas presenciales", "Forro personalizado", "Kit de viaje para el traje"],
    images: [px(2897883), px(34588167), px(325876)],
    bookedDates: [],
    popularity: 57,
  },
  {
    id: "limo-prime-mx",
    name: "Limo Prime MX",
    category: "autos-limosinas",
    categoryLabel: "Renta de Autos y Limosinas",
    location: "CDMX",
    basePrice: 7500,
    priceUnit: "por evento",
    rating: 4.8,
    reviews: 134,
    verified: true,
    fechas2026: true,
    tagline: "Limosina stretch y autos de lujo con chofer por 5 horas.",
    includes: ["5 horas de servicio", "Chofer uniformado", "Barra de cortesía", "Decoración del auto"],
    images: [px(5425443), px(9151813), px(1164778)],
    bookedDates: ["2026-09-12", "2026-09-19", "2026-10-17"],
    popularity: 89,
  },
  {
    id: "clasicos-de-epoca",
    name: "Clásicos de Época",
    category: "autos-limosinas",
    categoryLabel: "Renta de Autos y Limosinas",
    location: "Querétaro",
    basePrice: 9800,
    priceUnit: "por evento",
    rating: 4.9,
    reviews: 71,
    verified: true,
    fechas2026: true,
    tagline: "Autos clásicos restaurados para una entrada inolvidable.",
    includes: ["Auto clásico restaurado", "Sesión de fotos 30 min", "Chofer de época", "Ruta escénica incluida"],
    images: [px(30452995), px(32632282), px(30889938)],
    bookedDates: ["2026-10-03", "2026-10-24"],
    popularity: 78,
  },
  {
    id: "valet-y-traslados-aura",
    name: "Aura Traslados VIP",
    category: "autos-limosinas",
    categoryLabel: "Renta de Autos y Limosinas",
    location: "Guadalajara",
    basePrice: 5600,
    priceUnit: "por evento",
    rating: 4.7,
    reviews: 93,
    verified: false,
    fechas2026: false,
    tagline: "Vans y SUVs para invitados VIP, aeropuerto y after party.",
    includes: ["3 SUVs con chofer", "Traslado aeropuerto", "Servicio after party", "Coordinación de rutas"],
    images: [px(210019), px(20711173), px(34588167)],
    bookedDates: ["2026-09-26"],
    popularity: 64,
  },
];

export const PRICE_RANGES = [
  { id: "0-10000", label: "Hasta $10,000", min: 0, max: 10000 },
  { id: "10000-20000", label: "$10,000 – $20,000", min: 10000, max: 20000 },
  { id: "20000-45000", label: "$20,000 – $45,000", min: 20000, max: 45000 },
  { id: "45000-plus", label: "Más de $45,000", min: 45000, max: Infinity },
] as const;

export function formatMXN(value: number) {
  return `$${value.toLocaleString("es-MX")} MXN`;
}
