"use client";

import { FadeImage } from "@/components/fade-image";

const services = [
  { id: 1, name: "DJ Set + Audio Profesional", description: "DJ, iluminación y sonido para una noche memorable", price: "$18,500 MXN", image: "https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" },
  { id: 2, name: "Banquete Signature", description: "Menú de tres tiempos, montaje y servicio incluido", price: "$950 MXN / persona", image: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" },
  { id: 3, name: "Foto y Video Cinemático", description: "Cobertura 4K, drone y entrega de highlights", price: "$24,000 MXN", image: "https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" },
  { id: 4, name: "Jardín Los Olivos", description: "Venue para hasta 180 invitados en la ciudad", price: "$42,000 MXN", image: "https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" },
  { id: 5, name: "Diseño Floral Editorial", description: "Flores de temporada, mesas y ceremonia", price: "$16,800 MXN", image: "https://images.pexels.com/photos/931179/pexels-photo-931179.jpeg?auto=compress&cs=tinysrgb&w=1400&h=900&dpr=2" },
  { id: 6, name: "Coordinación del Día", description: "Un equipo experto para que tú disfrutes", price: "$12,500 MXN", image: "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" },
];

export function CollectionSection() { return <section id="accessories" className="bg-background"><div className="px-5 py-16 sm:px-6 md:px-12 md:py-10 lg:px-20"><h2 className="text-balance font-serif text-3xl font-medium leading-tight tracking-tight text-foreground sm:text-4xl md:text-5xl">Proveedores que hacen que suceda.</h2><p className="mt-4 max-w-xl text-muted-foreground">Cotiza servicios confiables y aparta tu fecha sin sorpresas.</p></div><div className="pb-24"><div className="flex snap-x snap-mandatory gap-4 overflow-x-auto overscroll-x-contain px-5 pb-5 pr-8 sm:px-6 md:hidden">{services.map((service) => <ServiceCard key={service.id} service={service} mobile />)}</div><div className="hidden gap-8 px-6 md:grid md:grid-cols-3 md:px-12 lg:px-20">{services.map((service) => <ServiceCard key={service.id} service={service} />)}</div></div></section>; }
function ServiceCard({ service, mobile = false }: { service: typeof services[number]; mobile?: boolean }) { return <div className={`group ${mobile ? "w-[82vw] flex-shrink-0 snap-center sm:w-[70vw]" : ""}`}><div className="relative aspect-[2/3] overflow-hidden rounded-2xl bg-secondary"><FadeImage src={service.image} alt={service.name} fill className="object-cover transition-transform duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-background/85 px-3 py-1.5 text-[10px] font-medium uppercase tracking-wider text-foreground backdrop-blur">Proveedor verificado</span></div><div className="py-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-medium leading-snug text-foreground">{service.name}</h3><p className="mt-2 text-sm text-muted-foreground">{service.description}</p><button type="button" className="mt-5 min-h-11 rounded-full border border-border px-4 py-2 text-xs font-medium text-foreground transition-colors hover:bg-foreground hover:text-background">Cotizar / Apartar</button></div><span className="text-right text-base font-medium text-foreground">{service.price}</span></div></div></div>; }
