"use client";

import Image from "next/image";
import { useEffect, useRef, useState, useCallback } from "react";

export function PhilosophySection() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [left, setLeft] = useState(-100); const [right, setRight] = useState(100); const [opacity, setOpacity] = useState(1); const raf = useRef<number | null>(null);
  const update = useCallback(() => { if (!sectionRef.current) return; const rect = sectionRef.current.getBoundingClientRect(); const progress = Math.max(0, Math.min(1, -rect.top / (sectionRef.current.offsetHeight - window.innerHeight))); setLeft((1 - progress) * -100); setRight((1 - progress) * 100); setOpacity(1 - progress); }, []);
  useEffect(() => { const onScroll = () => { if (raf.current) cancelAnimationFrame(raf.current); raf.current = requestAnimationFrame(update); }; window.addEventListener("scroll", onScroll, { passive: true }); update(); return () => { window.removeEventListener("scroll", onScroll); if (raf.current) cancelAnimationFrame(raf.current); }; }, [update]);
  return <section id="products" className="bg-background"><div ref={sectionRef} className="relative" style={{ height: "200vh" }}><div className="sticky top-0 flex h-screen items-center justify-center"><div className="relative w-full"><div className="absolute inset-0 z-0 flex items-center justify-center" style={{ opacity }}><h2 className="px-6 text-center font-serif text-[12vw] leading-[0.95] tracking-tighter text-foreground md:text-[10vw] lg:text-[8vw]">Celebra a tu manera.</h2></div><div className="relative z-10 grid grid-cols-1 gap-4 px-6 md:grid-cols-2 md:px-12 lg:px-20"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl" style={{ transform: `translate3d(${left}%,0,0)` }}><Image src="https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1400&q=85" alt="Música y DJ para eventos" fill className="object-cover" /><span className="absolute bottom-6 left-6 rounded-full bg-white/20 px-4 py-2 text-sm font-medium text-white backdrop-blur-md">Música y DJ</span></div><div className="relative aspect-[4/3] overflow-hidden rounded-2xl" style={{ transform: `translate3d(${right}%,0,0)` }}><Image src="https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1400&q=85" alt="Catering y banquetes" fill className="object-cover" /><span className="absolute bottom-6 left-6 rounded-full bg-white/20 px-4 py-2 text-sm font-medium text-white backdrop-blur-md">Catering Premium</span></div></div></div></div></div><div className="px-6 py-20 md:px-12 md:py-28 lg:px-20 lg:py-36"><div className="text-center"><p className="text-xs uppercase tracking-widest text-muted-foreground">Momentum marketplace</p><p className="mt-8 text-center text-3xl leading-relaxed text-muted-foreground">Música, banquetes, foto, video, venues y decoración. Planea cada detalle con proveedores verificados y cotizaciones claras.</p></div></div></section>;
}
